// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_cognito_region': 'eu-west-2',
    'aws_resource_name_prefix': 'admin pool',
    'aws_sign_in_enabled': 'enable',
    'aws_sign_up_enabled': 'enable',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'eu-west-2_W0b5mSPDM',
    'aws_user_pools_mfa_type': 'ON',
    'aws_user_pools_web_client_id': '3f3kbd98uaaieq4vc74g2qp7ts',
};

export default awsmobile;
